import type { Metadata } from "next"
import { Roboto } from "next/font/google"
import "./globals.css"
import { ThemeProvider } from "./providers/theme-provider"

const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${roboto.className} antialiased`}>
        <ThemeProvider 
      attribute="class"
      defaultTheme="system"
      disableTransitionOnChange
      enableSystem>
        {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
